### ISSUE TITLE
FEATURE: possibility to open source file from the tree

### ISSUE THREAD

**Issue by qyloxe** [bxantus/mdoc#3]
This is a GREAT extension! One of the most useful and must have in vs code ecosystem!

I have a little suggestion, which would improve usability: it should be possible to just open a source .md file directly from the items tree in the panel. This allow to quick change/edit source markdown file and let the tree in panel update. Without this, it's sometimes quite unconvenient to locate original source file.

**Comment by bxantus** [comment]
Thanks for the feedback! Any other requests are welcome!

The proposed feature is not that hard to implement, will try to do it, if I have a little spare time.

I think I will add it to the context menu, with the label `Open source`.

**Comment by bxantus** [comment]
@qyloxe please check the newest update (version 1.2.1), it should work as requested (check the changelog for details)

**Comment by qyloxe** [comment]
Works like a charm! Thanks!
