### ISSUE TITLE
Creating html docs

### ISSUE THREAD

**Issue by stephenberry** [bxantus/mdoc#5]
I really like this approach. I'm just wondering if you have a recommended approach for getting html documentation from this setup. Is there another library that you use? Thanks!

**Comment by bxantus** [comment]
For html documentation I would use a similar approach: only convert markdown to html when needed (ex. the current page you're viewing).
So I would always retrieve docs in markdown format, and there would be a webapp (mdoc for web), which you'll start up with the repo link, and would index the docs in local storage.

Hope this answers your question!

**Comment by stephenberry** [comment]
Thanks for your thoughts on this. That is helpful. Feel free to close this issue.
