### ISSUE TITLE
Remote file is rendered weirdly

### ISSUE THREAD

**Issue by thany** [bxantus/mdoc#9]
When linking to, or putting in the index.md file a remote file, which would be a documentation file on Github, it renders like this:

![image](https://user-images.githubusercontent.com/152227/112844094-9e030880-90a3-11eb-9079-7eee501f9823.png)

That ain't too useful, if we decide on online documentation (versus local).

When I open the same file in my browser, I get to see the linked documentation file as intended.

**Comment by bxantus** [comment]
You've probably linked to a generated html view of the documentation (at least based on the screenshot I guess this is the case).
You should always link to the raw URL (pointing to the markdown file content).
If this isn't the case please provide me with the concrete example (link) to check it more thoroughly.

Please check if this solves the issue.
